name: Pull Request Info tst

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get Pull Request Info
      run: |
        echo "Hello World"
        echo "Autor: ${{ github.actor }}"
        echo "Último commit: $(git log -1 --pretty=format:'%H')"
        echo "Cambios entre el último commit y el default branch:"
        git diff ${{ github.event.before }} ${{ github.sha }}
